apps/carrinho/urls.py
from urllib.parse import urlparse
from django.urls import path
from .views import carrinho_detalhado

app_name = 'carrinho'

urlpatterns =[
    path('', carrinho_detalhado, name='carrinho_detalhado'),
]

apps/roupas/urls.py
from django.urls import URLPattern, path
from .views import *

app_name = 'roupas'

urlpatterns =[
    path('', home, name='home'),
    path('produtos', produtos, name='produtos'),
    path('categoria/<slug:slug>/', produtos, name='produtos_por_categoria'),
    path('produtos/<slug:slug>/', produto_detalhado, name='produtos_detalhados'),
]

apps/usuarios/urls.py
from django.urls import URLPattern, path
from .views import *

app_name = 'usuarios'

urlpatterns =[
    path('login', login, name='login'),
]

loja_de_roupas/urls.py
import debug_toolbar
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('roupas.urls')),
    path('usuarios/', include('usuarios.urls')),
    path('pages/', include('pages.urls')),
    path('products/', include('products.urls')),
    path('carrinho/', include('carrinho.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += [path('__debug__/', include(debug_toolbar.urls))]

templates/partials/_footer.html
{%  load static %}

<footer>
    <div class="container-footer">
        <ul>
            <li><a href="">Home</a></li>
            <li><a href="">loja</a></li>
            <li><a href="">Contato</a></li>
            <li><a href="">Sobre</a></li>
        </ul>
        <ul>
            <li><a href="">FAQ</a></li>
            <li><a href="">Envios e Devoluções</a></li>
            <li><a href="">Política da Loja</a></li>
            <li><a href="">Pagamentos</a></li>
        </ul>
        <ul>
            <li><a href="">jaquelinerodrigues@gmail.com</a></li>
            <li>Rua Principal S/N</li>
            <li>Imperatriz-MA - 65909-001</li>
            <li>Tel: (99) 981126621</li>
        </ul>
        <h5>Jaqueline Rodrigues</h5>
    </div>
</footer>

templates/partials/_header.html
{% load static %}

<header>
    <h1 id="tituo-h1-principal">Jaqueline Rodrigues</h1>
    <nav>
        <ul>
            <div class="itens-navbar">
                <li><a href="{% url 'roupas:home' %}">Home</a></li>
                <li><a href="{% url 'roupas:produtos'%}">Produtos</a></li>
            </div>
            <li class="canto-direito-navbar-login">
                <a href="{% url 'usuarios:login' %}"><span class="material-symbols-outlined">account_circle</span></a>
            </li>
            <li class="canto-direito-navbar-carrinho">
                <a href="{% url 'carrinho:carrinho_detalhado' %}"><span class="material-symbols-outlined">shopping_cart</span></a>
            </li>
        </ul>
    </nav>
</header>